kind: ConfigMap
apiVersion: v1
metadata:
  name: hexagonal
  namespace: dev
data:
  ENVIRONMENT: development
  SERVER_REST_PORT: "5000"
  POSTGRESQL_DB: {"host": "localhost", "port": 5435, "ssl": false, "db": "postgres", "password": "12345", "user": "postgres", "syncronize": true }
  MONGODB_DB: {"host": "localhost", "port": 27017, "ssl": false, "db": "test", "password": "", "user": "", "syncronize": false }
  MAILER_CONFIG: {"email": "", "secretKey": "", "service": "gmail" }
  SECRET_TOKEN: 12345