components:
  schemas:
    user:
      type: object
      properties:
        name:
          type: string
          description: The user's name.
        lastname:
          type: string
          description: The user's last name.
        email:
          type: string
          format: email
          description: The user's email address.
        password:
          type: string
          description: The user's password.

    userRecord:
      type: object
      properties:
        id:
          type: number
          description: The user's unique identifier.
        name:
          type: string
          description: The user's name.
        lastname:
          type: string
          description: The user's last name.
        email:
          type: string
          format: email
          description: The user's email address.
        password:
          type: string
          description: The user's password.

    logIn:
      type: object
      properties:
        email:
          type: string
          format: email
          description: The user's email address.
        password:
          type: string
          description: The user's password.