apiVersion: v1
kind: Service
metadata:
  name: hexagonal
  namespace: dev
spec:
  selector:
    app: hexagonal
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 30000